### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by ranggirexa** [sanjeev309/face-recognition-dlib-tensorflow-knn#1]
train_indices = np.random.choice(len(x_),round(len(x_) * 0.8),replace=False)

what this line for?
thank you

**Comment by sanjeev309** [comment]
Since the issue was closed before I could answer, I assume you figured it out. Answering this for completeness: 

np.random.choice(a,b) returns a list of b random numbers between 0 and a. This is used to do test-train split the old-fashioned way where 0.8 is the train split percentage (80%).

**Comment by ranggirexa** [comment]
thanks for your explanation sir
